### ISSUE TITLE
CoreNlpPaser: No roots in graph

### ISSUE THREAD

**Issue by alex-j-j** [dkpro/dkpro-core#1026]
For some sentences, CoreNlpParser throws an exception:

```
java.lang.RuntimeException: No roots in graph:
dep                 reln                gov                 
---                 ----                ---                 

Find where this graph was created and make sure you're adding roots.
	at edu.stanford.nlp.semgraph.SemanticGraph.getFirstRoot(SemanticGraph.java:790)
	at edu.stanford.nlp.semgraph.semgrex.SemgrexPattern.matcher(SemgrexPattern.java:231)
	at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.demoteQuantificationalModifiers(UniversalEnglishGrammaticalStructure.java:1724)
	at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.addEnhancements(UniversalEnglishGrammaticalStructure.java:871)
	at edu.stanford.nlp.trees.GrammaticalStructure.typedDependenciesEnhancedPlusPlus(GrammaticalStructure.java:924)
	at edu.stanford.nlp.semgraph.SemanticGraphFactory.makeFromTree(SemanticGraphFactory.java:249)
	at edu.stanford.nlp.semgraph.SemanticGraphFactory.generateEnhancedPlusPlusDependencies(SemanticGraphFactory.java:129)
	at edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations(ParserAnnotatorUtils.java:67)
	at edu.stanford.nlp.pipeline.ParserAnnotator.finishSentence(ParserAnnotator.java:297)
	at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:267)
	at edu.stanford.nlp.pipeline.SentenceAnnotator$AnnotatorProcessor.process(SentenceAnnotator.java:31)
	at edu.stanford.nlp.pipeline.SentenceAnnotator$AnnotatorProcessor.process(SentenceAnnotator.java:21)
	at edu.stanford.nlp.util.concurrent.MulticoreWrapper$CallableJob.call(MulticoreWrapper.java:255)
	at edu.stanford.nlp.util.concurrent.MulticoreWrapper$CallableJob.call(MulticoreWrapper.java:236)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I am still investigating, but I think this comes from very short sentences, maybe for sentences with only one word. It definitely happens if the sentence contains only a single-character-token.

**Comment by reckart** [comment]
Sounds like it may be a CoreNLP issue and not a DKPro Core issue. If you can reproduce it in DKPro Core, could you also try if you can reproduce it using plain CoreNLP?

**Comment by bheinzerling** [comment]
This happens in plain CoreNLP when using the recently introduced enhancedPlusPlusDependencies dependency types. I've never seen it for basicDependencies or enhancedDependencies.

**Comment by alex-j-j** [comment]
@bheinzerling can you reproduce this with CoreNLP 3.7.0? I tried it by command line and the parser works for strings like "." or "..." which always crash with DKPro.
