### ISSUE TITLE
Make handling of DocumentMetaData configurable in some readers

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#1135]
Especially for the BinaryCasReader and the XmiReaders, it makes sense to make the handling of the DKPro Core DocumentMetadataAnnotation configurable. Allow choosing between

- if it is there, override it (or not)
- if it is not there, add it (or not)
 
In principle, this could even be added to ResourceCollectionReaderBase, but let's first see how useful this proves with these two readers.

**Comment by schrieveslaach** [comment]
@reckart, this change requires me to configure the `XmiReader.PARAM_ADD_DOCUMENT_METADATA` paramter to `false`. For example, I create a JCas object:

```java
@SneakyThrows(UIMAException.class)
    public static JCas createHelloWorld() {
        JCas jCas = JCasFactory.createText("Hello World.");

        DocumentMetaData metaData = new DocumentMetaData(jCas);
        metaData.setDocumentBaseUri("https://en.wikipedia.org/wiki/");
        metaData.setDocumentUri("https://en.wikipedia.org/wiki/Hello_World");
        metaData.setDocumentId("Hello-World");
        metaData.setDocumentTitle("Hello_World");
        metaData.addToIndexes();

        jCas.setDocumentLanguage("en");

        Sentence sentence = new Sentence(jCas, 0, 12);
        sentence.addToIndexes();

        Paragraph paragraph = new Paragraph(jCas, 0, 12);
        paragraph.addToIndexes();

        MappingProvider mappingProvider = createPosMappingProvider(
                null,
                "ud",
                jCas.getDocumentLanguage());
        mappingProvider.configure(jCas.getCas());

        Token token = new Token(jCas, 0, 5);
        token.addToIndexes();

        POS pos = (POS) jCas.getCas().createAnnotation(mappingProvider.getTagType("UH"), 6, 14);
        pos.setPosValue("UH");
        pos.addToIndexes();

        token = new Token(jCas, 6, 11);
        token.addToIndexes();

        pos = (POS) jCas.getCas().createAnnotation(mappingProvider.getTagType("NOUN"), 6, 14);
        pos.setPosValue("NOUN");
        pos.addToIndexes();

        token = new Token(jCas, 11, 12);
        token.addToIndexes();

        pos = (POS) jCas.getCas().createAnnotation(mappingProvider.getTagType("PUNCT"), 6, 14);
        pos.setPosValue("PUNCT");
        pos.addToIndexes();

        return jCas;
    }
```

Then, I store it somewhere.

```java
        runPipeline(createHelloWorld(),
                createEngineDescription(
                        XmiWriter.class,
                        XmiWriter.PARAM_TARGET_LOCATION, testDirectory
                )
        );
```

when I read it with the `XmiReader` it fails with following configuration.

```java
createReaderDescription(
                XmiReader.class,
                XmiReader.PARAM_SOURCE_LOCATION, new File(testDirectory, "Hello_World.xmi")
        );
```

I need to use following reader description:

```java
createReaderDescription(
                XmiReader.class,
                XmiReader.PARAM_SOURCE_LOCATION, new File(testDirectory, "Hello_World.xmi"),
                XmiReader.PARAM_ADD_DOCUMENT_METADATA, false
        );
```

Is this desired behavior?

**Comment by reckart** [comment]
You are writing an XMI document which contains a `DocumentMetaData` annotation.

Then you read that document.

By default, the XmiReader should then not do anything:

- `PARAM_ADD_DOCUMENT_METADATA = true` (default) - does not apply because a `DocumentMetaData` annotation already exists. It should only add a `DocumentMetaData` if there is no `DocumentMetaData` yet.
- `PARAM_OVERRIDE_DOCUMENT_METADATA = false` (default) - should not touch the existing `DocumentMetaData` because it is not enabled.

What kind of failure do you see?

**Comment by schrieveslaach** [comment]
Here is the log:

```
/usr/lib/jvm/java-8-openjdk/bin/java -javaagent:/usr/share/intellij-idea-ultimate-edition/lib/idea_rt.jar=44399:/usr/share/intellij-idea-ultimate-edition/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-openjdk/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk/jre/lib/rt.jar:/tmp/test/target/classes:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.io.xmi-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.io.xmi-asl-1.9.0-20170924.214717-447.jar:/home/marc/.m2/repository/org/apache/uima/uimaj-core/2.10.1/uimaj-core-2.10.1.jar:/home/marc/.m2/repository/org/apache/uima/uimafit-core/2.3.0/uimafit-core-2.3.0.jar:/home/marc/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar:/home/marc/.m2/repository/org/springframework/spring-context/3.2.16.RELEASE/spring-context-3.2.16.RELEASE.jar:/home/marc/.m2/repository/org/springframework/spring-aop/3.2.16.RELEASE/spring-aop-3.2.16.RELEASE.jar:/home/marc/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/marc/.m2/repository/org/springframework/spring-expression/3.2.16.RELEASE/spring-expression-3.2.16.RELEASE.jar:/home/marc/.m2/repository/org/springframework/spring-beans/3.2.16.RELEASE/spring-beans-3.2.16.RELEASE.jar:/home/marc/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.io-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.api.io-asl-1.9.0-20170924.214637-447.jar:/home/marc/.m2/repository/org/apache/ant/ant/1.8.1/ant-1.8.1.jar:/home/marc/.m2/repository/org/apache/ant/ant-launcher/1.8.1/ant-launcher-1.8.1.jar:/home/marc/.m2/repository/it/unimi/dsi/fastutil/7.0.9/fastutil-7.0.9.jar:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.featurepath-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.api.featurepath-asl-1.9.0-20170924.214636-447.jar:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.ner-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.api.ner-asl-1.9.0-20170924.214638-447.jar:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.segmentation-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.api.segmentation-asl-1.9.0-20170924.214640-447.jar:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.resources-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.api.resources-asl-1.9.0-20170924.214640-447.jar:/home/marc/.m2/repository/org/apache/commons/commons-compress/1.14/commons-compress-1.14.jar:/home/marc/.m2/repository/org/apache/maven/maven-model/3.0.5/maven-model-3.0.5.jar:/home/marc/.m2/repository/org/apache/ivy/ivy/2.3.0/ivy-2.3.0.jar:/home/marc/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar:/home/marc/.m2/repository/org/tukaani/xz/1.5/xz-1.5.jar:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.parameter-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.api.parameter-asl-1.9.0-20170924.214639-447.jar:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.metadata-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.api.metadata-asl-1.9.0-20170924.214638-447.jar:/home/marc/.m2/repository/org/apache/uima/uimaj-document-annotation/2.10.1/uimaj-document-annotation-2.10.1.jar:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl-1.9.0-20170924.214637-447.jar:/home/marc/.m2/repository/org/springframework/spring-core/3.2.16.RELEASE/spring-core-3.2.16.RELEASE.jar:/home/marc/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/marc/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar App
Sep 25, 2017 4:48:44 PM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase configure
INFORMATION: Producing resource from jar:file:/home/marc/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl/1.9.0-SNAPSHOT/de.tudarmstadt.ukp.dkpro.core.api.lexmorph-asl-1.9.0-20170924.214637-447.jar!/de/tudarmstadt/ukp/dkpro/core/api/lexmorph/tagset/en-ud-pos.map
Sep 25, 2017 4:48:44 PM de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase loadResource
INFORMATION: Producing resource took 1ms
Sep 25, 2017 4:48:45 PM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase scan(411)
INFORMATION: Scanning [file:/tmp/Hello_World.xmi]
Sep 25, 2017 4:48:45 PM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase initialize(237)
INFORMATION: Found [1] resources to be read
Sep 25, 2017 4:48:45 PM de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase nextFile(336)
INFORMATION: 0 of 1: file:/tmp/Hello_World.xmi
Exception in thread "main" java.lang.IllegalStateException: CAS already contains DocumentMetaData
	at de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData.create(DocumentMetaData.java:302)
	at de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase.initCas(ResourceCollectionReaderBase.java:610)
	at de.tudarmstadt.ukp.dkpro.core.api.io.ResourceCollectionReaderBase.initCas(ResourceCollectionReaderBase.java:591)
	at de.tudarmstadt.ukp.dkpro.core.io.xmi.XmiReader.getNext(XmiReader.java:103)
	at org.apache.uima.fit.pipeline.JCasIterator.next(JCasIterator.java:140)
	at App.main(App.java:81)
```

With full example code:

```java
import de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.POS;
import de.tudarmstadt.ukp.dkpro.core.api.metadata.type.DocumentMetaData;
import de.tudarmstadt.ukp.dkpro.core.api.resources.MappingProvider;
import de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Paragraph;
import de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Sentence;
import de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token;
import de.tudarmstadt.ukp.dkpro.core.io.xmi.XmiReader;
import de.tudarmstadt.ukp.dkpro.core.io.xmi.XmiWriter;
import org.apache.uima.fit.factory.JCasFactory;
import org.apache.uima.jcas.JCas;

import java.io.File;

import static de.tudarmstadt.ukp.dkpro.core.api.resources.MappingProviderFactory.createPosMappingProvider;
import static org.apache.uima.fit.factory.AnalysisEngineFactory.createEngineDescription;
import static org.apache.uima.fit.factory.CollectionReaderFactory.createReaderDescription;
import static org.apache.uima.fit.pipeline.SimplePipeline.iteratePipeline;
import static org.apache.uima.fit.pipeline.SimplePipeline.runPipeline;

public class App {

    public static JCas createHelloWorld() throws Exception {
        JCas jCas = JCasFactory.createText("Hello World.");

        DocumentMetaData metaData = new DocumentMetaData(jCas);
        metaData.setDocumentBaseUri("https://en.wikipedia.org/wiki/");
        metaData.setDocumentUri("https://en.wikipedia.org/wiki/Hello_World");
        metaData.setDocumentId("Hello-World");
        metaData.setDocumentTitle("Hello_World");
        metaData.addToIndexes();

        jCas.setDocumentLanguage("en");

        Sentence sentence = new Sentence(jCas, 0, 12);
        sentence.addToIndexes();

        Paragraph paragraph = new Paragraph(jCas, 0, 12);
        paragraph.addToIndexes();

        MappingProvider mappingProvider = createPosMappingProvider(
                null,
                "ud",
                jCas.getDocumentLanguage());
        mappingProvider.configure(jCas.getCas());

        Token token = new Token(jCas, 0, 5);
        token.addToIndexes();

        POS pos = (POS) jCas.getCas().createAnnotation(mappingProvider.getTagType("UH"), 6, 14);
        pos.setPosValue("UH");
        pos.addToIndexes();

        token = new Token(jCas, 6, 11);
        token.addToIndexes();

        pos = (POS) jCas.getCas().createAnnotation(mappingProvider.getTagType("NOUN"), 6, 14);
        pos.setPosValue("NOUN");
        pos.addToIndexes();

        token = new Token(jCas, 11, 12);
        token.addToIndexes();

        pos = (POS) jCas.getCas().createAnnotation(mappingProvider.getTagType("PUNCT"), 6, 14);
        pos.setPosValue("PUNCT");
        pos.addToIndexes();

        return jCas;
    }

    public static void main(String[] args) throws Exception {
        runPipeline(createHelloWorld(),
                createEngineDescription(
                        XmiWriter.class,
                        XmiWriter.PARAM_TARGET_LOCATION, "/tmp"
                )
        );

        JCas jCas = iteratePipeline(createReaderDescription(
                XmiReader.class,
                XmiReader.PARAM_SOURCE_LOCATION, new File("/tmp", "Hello_World.xmi")
        )).iterator().next();

        System.out.println(jCas);
    }
}
```

**Comment by reckart** [comment]
You should not use `DocumentMetaData metaData = new DocumentMetaData(jCas);` but rather `DocumentMetaData metaData = DocumentMetaData.create(jCas);`

**Comment by schrieveslaach** [comment]
OK, thanks!
