### ISSUE TITLE
NullPointerException when reading CoNLL 2012

### ISSUE THREAD

**Issue by nilsreiter** [dkpro/dkpro-core#1188]
I'm trying to read a file  that has been exported with the CoNLL2012Writer, but only contains coreference information (i.e., most columns contain a dash, see below for an example). I disabled most of the CoNLL2012Reader (`Conll2012Reader.PARAM_READ_CONSTITUENT, false` etc.), but it still throws this exception:
```
Caused by: java.lang.NullPointerException
	at de.tudarmstadt.ukp.dkpro.core.io.penntree.PennTreeUtils.getPreTerminals(PennTreeUtils.java:307) ~[de.tudarmstadt.ukp.dkpro.core.io.penntree-asl-1.9.0.jar:?]
	at de.tudarmstadt.ukp.dkpro.core.io.penntree.PennTreeUtils.getPreTerminals(PennTreeUtils.java:301) ~[de.tudarmstadt.ukp.dkpro.core.io.penntree-asl-1.9.0.jar:?]
	at de.tudarmstadt.ukp.dkpro.core.io.penntree.PennTreeToJCasConverter.convertPennTree(PennTreeToJCasConverter.java:207) ~[de.tudarmstadt.ukp.dkpro.core.io.penntree-asl-1.9.0.jar:?]
	at de.tudarmstadt.ukp.dkpro.core.io.conll.Conll2012Reader.convert(Conll2012Reader.java:448) ~[de.tudarmstadt.ukp.dkpro.core.io.conll-asl-1.9.0.jar:?]

```

I think this can be solved by checking the `readConstituent` field before line [448](https://github.com/dkpro/dkpro-core/blob/b4dd9935598a7838a9caeb39f235ba682def7058/dkpro-core-io-conll-asl/src/main/java/de/tudarmstadt/ukp/dkpro/core/io/conll/Conll2012Reader.java#L448), but I don't know about side effects.

Example file:
```
BT2.conll   0   0       Herr     -            -         -    -   -          -         *             -
BT2.conll   0   1  Präsident     -            -         -    -   -          -         *             -
BT2.conll   0   2          !     -            -         -    -   -          -         *             -

BT2.conll   0   0      Meine     -            -         -    -   -          -         *             (18|(16)
BT2.conll   0   1      Damen     -            -         -    -   -          -         *             -
BT2.conll   0   2        und     -            -         -    -   -          -         *             -
BT2.conll   0   3     Herren     -            -         -    -   -          -         *             18)
BT2.conll   0   4          !     -            -         -    -   -          -         *             -
```

This is on version 1.9.0.

**Comment by reckart** [comment]
As far as I can tell from a quick glance, the converter down there shouldn't be called if `readConstituents` is not enabled. Should be an easy fix. Care to submit a PR?

**Comment by reckart** [comment]
Would be great to include a small unit test with your data along ;)

**Comment by nilsreiter** [comment]
Ok, but probably not today.
