### ISSUE TITLE
BratReader crashes when an annotation covers more than two spans of text

### ISSUE THREAD

**Issue by alaindesilets** [dkpro/dkpro-core#1378]
Use the attached Maven project to reproduce the bug: 
[TestBratNewlineBug.zip](https://github.com/dkpro/dkpro-core/files/3257669/TestBratNewlineBug.zip)

Run the `ReadBrat` program, feeding it the path to the `docs` directory (als on contained in the Maven project).

You will then get the following exception:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at de.tudarmstadt.ukp.dkpro.core.io.brat.internal.model.BratTextAnnotation.generateOffsetsString(BratTextAnnotation.java:132)
	at de.tudarmstadt.ukp.dkpro.core.io.brat.internal.model.BratTextAnnotation.parse(BratTextAnnotation.java:152)
	at de.tudarmstadt.ukp.dkpro.core.io.brat.internal.model.BratAnnotationDocument.read(BratAnnotationDocument.java:54)
	at de.tudarmstadt.ukp.dkpro.core.io.brat.BratReader.readAnnotations(BratReader.java:192)
	at de.tudarmstadt.ukp.dkpro.core.io.brat.BratReader.getNext(BratReader.java:184)
	at de.tudarmstadt.ukp.dkpro.core.api.io.JCasResourceCollectionReader_ImplBase.getNext(JCasResourceCollectionReader_ImplBase.java:41)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:100)
	at ReadBrat.main(ReadBrat.java:24)
```

This bug has been found to occur on both OSX and Windows.

The problem occurs on line 132 in BratTextAnnotation. It references offsetsList.get(i - 1), but such an index doesn't exist since nothing was added to offsetsList in the previous loop. 
 
The solution might be to replace

> offsetsList.get(i - 1).setEnd(effectiveEnd);

with

> offsetsList.get(offsetsList.size() - 1).setEnd(effectiveEnd);

We have tested this fix on a cloned version of dkpro-core and it seems to do the trick.

**Comment by reckart** [comment]
@alaindesilets would you like to do a PR? (see [contribution guidelines](https://dkpro.github.io/contributing/))

**Comment by alaindesilets** [comment]
Sure. I'll see about getting a contribution agreement in place from my
employer.

**Comment by alaindesilets** [comment]
Hum... it sounds like it would take weeks to have the corporate
contribution agreement signed by the NRC president. Probably best if you
guys do the change yourselves.
