### ISSUE TITLE
Proplem with Clearnlp SRL

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#553]
```
What steps will reproduce the problem?
1. I used clearnlp within dkpro 1.7, model variant is Ontonotes
2. I ran a pipeline with ClearNlpSegmenter, ClearNlpLemmatizer, ClearNlpDependencyParser,
ClearNlpSemanticRoleLabeler
3. Then I got exception when processing this sentence: "The Wasilla Bible Church in
Wasilla, Alaska was apparently attacked by an arsonist last night." If I block the
SRL, it works

What is the expected output? What do you see instead?
...
Caused by: java.lang.NullPointerException
	at com.clearnlp.dependency.DEPLibEn.getTopVerbChain(DEPLibEn.java:373)
	at com.clearnlp.dependency.DEPLibEn.labelReferentOfRelativeClause(DEPLibEn.java:354)
	at com.clearnlp.dependency.DEPLibEn.postLabel(DEPLibEn.java:300)
	at com.clearnlp.component.srl.EnglishSRLabeler.postLabel(EnglishSRLabeler.java:149)
	at com.clearnlp.component.srl.AbstractSRLabeler.label(AbstractSRLabeler.java:335)
	at com.clearnlp.component.srl.AbstractSRLabeler.processAux(AbstractSRLabeler.java:255)
	at com.clearnlp.component.srl.AbstractSRLabeler.process(AbstractSRLabeler.java:230)
	at de.tudarmstadt.ukp.dkpro.core.clearnlp.ClearNlpSemanticRoleLabeler.process(ClearNlpSemanticRoleLabeler.java:315)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	... 32 more


What version of the product are you using? On what operating system?
dkpro 1.7, MacOS 10.10.1

Please provide any additional information below.

```

Original issue reported on code.google.com by `nghiemtrid` on 2014-12-04 15:52:39

**Comment by reckart** [comment]
This is fixed in commits f31ac04 and 14ed41b.
