### ISSUE TITLE
MateMorphTagger test for Spanish fails with NPE

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-core#630]
MateMorphTagger test for Spanish fails with NPE.

anna v3.61
matetools-model-morphtagger-es-conll2009 v20130117.1

```
2015-05-25 17:54:44 ERROR [main] (AggregateAnalysisEngine_impl) - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
    at de.tudarmstadt.ukp.dkpro.core.matetools.MateMorphTagger.process(MateMorphTagger.java:189)
    at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
    at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
    at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
    at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
    at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
    at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:284)
    at de.tudarmstadt.ukp.dkpro.core.testing.TestRunner.runTest(TestRunner.java:99)
    at de.tudarmstadt.ukp.dkpro.core.testing.TestRunner.runTest(TestRunner.java:69)
    at de.tudarmstadt.ukp.dkpro.core.testing.TestRunner.runTest(TestRunner.java:44)
    at de.tudarmstadt.ukp.dkpro.core.matetools.MateMorphTaggerTest.runTest(MateMorphTaggerTest.java:142)
    at de.tudarmstadt.ukp.dkpro.core.matetools.MateMorphTaggerTest.testSpanish(MateMorphTaggerTest.java:102)
    ...
Caused by: java.lang.NullPointerException
    at de.tudarmstadt.ukp.dkpro.core.matetools.MateMorphTagger.process(MateMorphTagger.java:176)
    ... 39 more
```

**Comment by reckart** [comment]
I don't think there is anything we can do about it since this package is no longer maintained upstream. If anybody hits this and has an idea how to fix it, please feel free to comment here.
