### ISSUE TITLE
Custom Annotator and ResourceInitializationException

### ISSUE THREAD

**Issue by bwaltl** [dkpro/dkpro-core#678]
Hi,

I'm using DKPro and UIMAFit in a Web Application using the Play Framework. 
I can perfectly use the annotators provided by DKPro Core, such as BreakIteratorSegmenter, OpenNLP-Tagger, etc. to build an AnalsisEngine. But when i want to use a Custom Annotator to segment the sentences and tokens (namely LegalSentenceSegmenter) and which is stored in my local project I get a 
org.apache.uima.resource.ResourceInitializationException: Annotator class "informationExtraction.uimaannotators.LegalSentenceSegmenter" was not found. (Descriptor: <unknown>).

However, if i make an Analysis Engine which solely uses my Custom Annotator it works just fine:

            AnalysisEngine pipe = AnalysisEngineFactory.createEngine(LegalSentenceSegmenter.class);

But when I try to combine my annotator with the annotators from the packages provided by DKPro Core It leads to the error:

```
// tokenizer
AnalysisEngineDescription tokenizerDesc = createEngineDescription(LegalSentenceSegmenter.class);
// tagger
AnalysisEngineDescription taggerDesc = createEngineDescription(OpenNlpPosTagger.class);
// aggregate AE for basic pipe
AnalysisEngineDescription basicPipeDesc = AnalysisEngineFactory.createEngineDescription(tokenizerDesc, taggerDesc);
AnalysisEngine pipe = UIMAFramework.produceAnalysisEngine(basicPipeDesc); //—> throws an exception
```

StackTrace:

```
org.apache.uima.resource.ResourceInitializationException: Annotator class "informationExtraction.uimaannotators.LegalSentenceSegmenter" was not found. (Descriptor: <unknown>)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:219)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:169)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:371)
	at informationExtraction.Pipeline.defaultPipeline(Pipeline.java:83)
	at controllers.Application.runPipeline(Application.java:206)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:389)
	at Routes$$anonfun$routes$1$$anonfun$applyOrElse$16$$anonfun$apply$16.apply(routes_routing.scala:389)
	at play.core.Router$HandlerInvokerFactory$$anon$4.resultCall(Router.scala:264)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.invocation(Router.scala:255)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:55)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at play.core.j.JavaAction$$anonfun$11.apply(JavaAction.scala:82)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:492)
	at play.core.j.JavaAction$class.apply(JavaAction.scala:82)
	at play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1.apply(Router.scala:252)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:128)
	at scala.Option.map(Option.scala:145)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:128)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:121)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:483)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:519)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:496)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.ClassNotFoundException: informationExtraction.uimaannotators.LegalSentenceSegmenter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:216)
	... 61 more
```

I think that there is a simple solution out there, but I just cannot see it.
Thanks for your help!

Cheers,
Bernhard

**Comment by reckart** [comment]
I assume you are using Maven to depend on DKPro Core artifacts and that your webapp project is also a Maven project? Is the project that contains your annotator also a Maven project? Does your webapp depend on your local project via Maven?.

**Comment by bwaltl** [comment]
The web application itself is not a maven project. And the dependencies to the DKPro Core artifacts are handled with SBT. 
The web application and the Custom Annotator (.java - File) are in the same project, so there are no dependencies between them.

**Comment by reckart** [comment]
I have the feeling that you are hitting the problem that UIMA doesn't take the thread context classloader into account (https://issues.apache.org/jira/browse/UIMA-3692). 

However, if your project contains the class that UIMA should be looking for, it is strange that it cannot be located through the application class loader. I'm not familiar with Scala's/Play's handling of classloaders. Are you aware of any kind of classloader isolation it might perform?

**Comment by bwaltl** [comment]
After spending many hours on that issue I found a workaround with which i can live. I split the different annotators in different pipes, such that my local annotators and the annotators from DKPro are processed in different process calls. Between the calls I keep the JCas Object and reuse it in the second process call.

 // tokenizer
AnalysisEngine pipe = AnalysisEngineFactory.createEngine(LegalSentenceSegmenter.class);

JCas jCas = pipe.newJCas();
jCas.setDocumentText(plainText);
try {
    pipe.process(jCas);
} catch (AnalysisEngineProcessException aepe) {
    aepe.printStackTrace();
}

// tagger
AnalysisEngineDescription taggerDesc = createEngineDescription(OpenNlpPosTagger.class);

// aggregate AE for final pipe
AnalysisEngineDescription pipeDesc = AnalysisEngineFactory.createEngineDescription(taggerDesc);

// aggregate AE for final pipe
AnalysisEngine pipe2 = UIMAFramework.produceAnalysisEngine(pipeDesc);

try {
    pipe2.process(jCas);
} catch (AnalysisEngineProcessException aepe) {
    aepe.printStackTrace();
}

// clean up
jCas.reset();
pipe.destroy();
pipe2.destroy();

What do you think about this workaround? This might helps someone else facing the same problem...

Cheers

**Comment by reckart** [comment]
I think that's perfectly ok if it solves your problem. But I still don't see the cause of the problem. Expecially if the block of code you quoted above really appears as-is, I don't really see what causes the classloader problems. Does the trick somehow lie in the fact that you use `UIMAFramework.produceAnalysisEngine` in the second part? Does your workaround still work if you use `AnalysisEngineFactory.createEngine` instead?

**Comment by tobiaswaltl** [comment]
Actually, this was not the trick but the fault.
It works fine after replacing `UIMAFramework.produceAnalysisEngine` with `AnalysisEngineFactory.createEngine`.
Thanks for this hint!

**Comment by reckart** [comment]
Good it works for you :)

**Comment by outsideMyBox** [comment]
Hi,

I had the same issue using the Play Framework (2.4), though using Scala. Here are some comments that may help understand the problem in cases others stumble upon this error:

In development mode (command run) Play recompiles and performs a hot reload whenever the code is modified (no need to redeploy or use tools like JRebel!). To do so Play uses an additional class loader (ReloadableClassLoader) that loads the project's classes. This class loader is a child of the applicationLoader that loads the jar files.
By default UIMA uses Class.forName to locate the analysis components (see PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(...)) which works fine if they are in the applicationLoader (like the annotators from jar files) but not in the ReloadableClassLoader (like the custom annotators).

Another way to solve the issue is to define a UIMA extension classLoader:
 ``` Scala
val parentCL = this.getClass.getClassLoader // Let's suppose this code is part of the project loaded by ReloadableClassLoader
val uimaResourceManager = UIMAFramework.newDefaultResourceManager()
uimaResourceManager.setExtensionClassPath(parentCL, "/", true)
UIMAFramework.produceAnalysisEngine(myAnalysisComponent, uimaResourceManager)
```

**Comment by reckart** [comment]
@outsideMyBox cool! Can you say if Play Framework set the Thread classloader such that **if** UIMA properly used that by default, it would work out of the box. I am trying to push here [1] for a change in the UIMA framework to take the Thread classloader always into account if it exists because I am pretty sure it would avoid such problems as you describe them.

[1] https://issues.apache.org/jira/browse/UIMA-3692

**Comment by outsideMyBox** [comment]
Hi Richard. I had a look at the code and it seems that they use the Thread classloader for the reload mechanism, so it should work if I'm not mistaken.

**Comment by reckart** [comment]
You could use an **internal** API of uimaFIT to change the default resource manager that it creates. Via `ResourceManagerFactory.setResourceManagerCreator()`, you could tell it to always create a resource manager with  an extension classLoader (as you show above).

Mind, this is **internal** API - an unofficial extension point to test different strategies for resource managers and classloading. It may change or disappear in future versions of uimaFIT (or it might be promoted to an official API...).
