### ISSUE TITLE
NegativeArraySizeException in Mallet WordEmbeddings with large vocabulary

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#866]
With a large vocabulary size, I get the following exception:

    Jun 01, 2016 6:54:26 PM de.tudarmstadt.ukp.dkpro.core.mallet.wordembeddings.WordEmbeddingsEstimator collectionProcessComplete(80)
    INFO: Computing word embeddings...
    Vocab size: 6105270
    Exception in thread "main" java.lang.NegativeArraySizeException at cc.mallet.topics.WordEmbeddings.<init>(WordEmbeddings.java:100)
        at de.tudarmstadt.ukp.dkpro.core.mallet.wordembeddings.WordEmbeddingsEstimator.collectionProcessComplete(WordEmbeddingsEstimator.java:83)
        at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.collectionProcessComplete(PrimitiveAnalysisEngine_impl.java:330)
        at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.collectionProcessComplete(AggregateAnalysisEngine_impl.java:335)
        at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:155)
        at de.tudarmstadt.ukp.experiments.wdk.topicmodeling.wordembeddings.EstimateEmbeddings.doMain(EstimateEmbeddings.java:83)
        at de.tudarmstadt.ukp.experiments.wdk.topicmodeling.wordembeddings.EstimateEmbeddings.main(EstimateEmbeddings.java:61)

This is `WordEmbeddings.java:100`:

    weights = new double[numWords * stride];

where `stride = 2 * numColumns` and `numColumns` is the vector dimensionality, in my trial 300. This is apparently due to an integer overflow, because `numWords * stride` =  `numWords * 2 * numColumns` = `6105270 * 2 * 300` = 3663162000.

**Comment by carschno** [comment]
https://github.com/mimno/Mallet/issues/65

**Comment by carschno** [comment]
This needs to be resolved upstream, hence it can't be fixed here.
