### ISSUE TITLE
MaltParserTest.testGerman fails

### ISSUE THREAD

**Issue by maxxkia** [dkpro/dkpro-core#881]
When trying to build dkpro-core, I noticed that MaltParserTest.testGerman fails. We tried this on @betoboullosa 's machine and the result was the same.

test fails with the following stack trace:
```
2016-06-16 12:17:04 ERROR [main] (PrimitiveAnalysisEngine_impl) - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.tudarmstadt.ukp.dkpro.core.api.resources.CasConfigurableProviderBase.configure(CasConfigurableProviderBase.java:39)
	at de.tudarmstadt.ukp.dkpro.core.api.resources.ModelProviderBase.configure(ModelProviderBase.java:78)
	at de.tudarmstadt.ukp.dkpro.core.maltparser.MaltParser.process(MaltParser.java:306)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:284)
	at de.tudarmstadt.ukp.dkpro.core.testing.TestRunner.runTest(TestRunner.java:144)
	at de.tudarmstadt.ukp.dkpro.core.testing.TestRunner.runTest(TestRunner.java:100)
	at de.tudarmstadt.ukp.dkpro.core.testing.TestRunner.runTest(TestRunner.java:54)
	at de.tudarmstadt.ukp.dkpro.core.maltparser.MaltParserTest.runTest(MaltParserTest.java:716)
	at de.tudarmstadt.ukp.dkpro.core.maltparser.MaltParserTest.testGerman(MaltParserTest.java:491)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.IOException: Model URL resolves to properties at [jar:file:/home/local/Org/User/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.maltparser-model-parser-de-linear/1.7/de.tudarmstadt.ukp.dkpro.core.maltparser-model-parser-de-linear-1.7.jar!/de/tudarmstadt/ukp/dkpro/core/maltparser/lib/parser-de-linear.properties] but no redirect property [location] found there.
	at de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase.followRedirects(ResourceObjectProviderBase.java:619)
	at de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase.configure(ResourceObjectProviderBase.java:567)
	at de.tudarmstadt.ukp.dkpro.core.api.resources.CasConfigurableProviderBase.configure(CasConfigurableProviderBase.java:36)
	... 41 more
2016-06-16 12:17:04 ERROR [main] (AggregateAnalysisEngine_impl) - Exception occurred
org.apache.uima.analysis_engine.AnalysisEngineProcessException
	at de.tudarmstadt.ukp.dkpro.core.api.resources.CasConfigurableProviderBase.configure(CasConfigurableProviderBase.java:39)
	at de.tudarmstadt.ukp.dkpro.core.api.resources.ModelProviderBase.configure(ModelProviderBase.java:78)
	at de.tudarmstadt.ukp.dkpro.core.maltparser.MaltParser.process(MaltParser.java:306)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:48)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:385)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:308)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:570)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:412)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:344)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:265)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:269)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:284)
	at de.tudarmstadt.ukp.dkpro.core.testing.TestRunner.runTest(TestRunner.java:144)
	at de.tudarmstadt.ukp.dkpro.core.testing.TestRunner.runTest(TestRunner.java:100)
	at de.tudarmstadt.ukp.dkpro.core.testing.TestRunner.runTest(TestRunner.java:54)
	at de.tudarmstadt.ukp.dkpro.core.maltparser.MaltParserTest.runTest(MaltParserTest.java:716)
	at de.tudarmstadt.ukp.dkpro.core.maltparser.MaltParserTest.testGerman(MaltParserTest.java:491)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.io.IOException: Model URL resolves to properties at [jar:file:/home/local/Org/User/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.maltparser-model-parser-de-linear/1.7/de.tudarmstadt.ukp.dkpro.core.maltparser-model-parser-de-linear-1.7.jar!/de/tudarmstadt/ukp/dkpro/core/maltparser/lib/parser-de-linear.properties] but no redirect property [location] found there.
	at de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase.followRedirects(ResourceObjectProviderBase.java:619)
	at de.tudarmstadt.ukp.dkpro.core.api.resources.ResourceObjectProviderBase.configure(ResourceObjectProviderBase.java:567)
	at de.tudarmstadt.ukp.dkpro.core.api.resources.CasConfigurableProviderBase.configure(CasConfigurableProviderBase.java:36)
	... 41 more

```

Checking the stack trace it shows that java is complaining about model location:
```
Caused by: java.io.IOException: Model URL resolves to properties at [jar:file:/home/local/Org/User/.m2/repository/de/tudarmstadt/ukp/dkpro/core/de.tudarmstadt.ukp.dkpro.core.maltparser-model-parser-de-linear/1.7/de.tudarmstadt.ukp.dkpro.core.maltparser-model-parser-de-linear-1.7.jar!/de/tudarmstadt/ukp/dkpro/core/maltparser/lib/parser-de-linear.properties] but no redirect property [location] found there.
```

I looked up the properties file and obviously the problem is that it doesn't contain any location property. Here I paste the contents of the properties file:
```
#Stanford NLP tools model description
#Tue, 17 Apr 2012 12:46:05 +0200

downloaded=2012/04/17 12\:46
tool=parser
language=de
variant=linear
md5=b24b584bb18e5fad940c5945bdbb0c6b
sha1=2c52ea8f898efbc650bb04196c36fe344df9e425
```

Looking at the header of this file it already looks like a wrong file. Why "Stanford NLP tools"?!

**Comment by maxxkia** [comment]
@reckart Do you have any idea?

**Comment by reckart** [comment]
There are no official models for maltparser.

**Comment by maxxkia** [comment]
so should _ignore_ tag be added to this test?

**Comment by reckart** [comment]
The test only runs if the profile "use-proprietary-resources" is enabled - which by default is disabled. So in the normal case this test doesn't run anyway.

**Comment by maxxkia** [comment]
That's right disabling this profile resolved the problem.
