### ISSUE TITLE
Mallet: Declare Trove dependency version explicitly

### ISSUE THREAD

**Issue by carschno** [dkpro/dkpro-core#947]
I have an independent Maven project in which I have a dependency to `dkpro-core-mallet`. It fails to compile with the following message:

```
Exception in thread "main" java.lang.NoClassDefFoundError: gnu/trove/TObjectIntHashMap
  at cc.mallet.types.Alphabet.<init>(Alphabet.java:63)
  at cc.mallet.types.Alphabet.<init>(Alphabet.java:82)
  at cc.mallet.pipe.TokenSequence2FeatureSequence.<init>(TokenSequence2FeatureSequence.java:35)
  at de.tudarmstadt.ukp.dkpro.core.mallet.MalletModelTrainer.initialize(MalletModelTrainer.java:155)
  at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:266)
  at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:170)
  at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
  at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
  at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
  at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
  at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
  at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
  at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
  at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
  at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
  at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
  at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
  at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:331)
  at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:448)
  at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:139)
  at Word2Vec.main(Word2Vec.java:29)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: gnu.trove.TObjectIntHashMap
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 26 more
```

This happens because Mallet requires Trove version 2.x, while 3.x is the most recent one. However, the dkpro-core-mallet module itself compiles fine and I was expecting it to pass its dependencies on through Maven because it inherits the required Trove dependency, here's an extract of the output from `dkpro-core/dkpro-core-mallet-asl$ mvn dependency:tree`:

```
+- cc.mallet:mallet:jar:2.0.8:compile
  |  +- [...]
  |  +- net.sf.trove4j:trove4j:jar:2.0.2:compile
```

The reason for my project failing is revealed through the output of the same command, showing a different result:

```
|  +- cc.mallet:mallet:jar:2.0.8:compile
|  |  +- [...]
|  |  +- net.sf.trove4j:trove4j:jar:3.0.1:compile
```

It somehow inherits Trove 3.0.1 instead of 2.0.2 and thus fails. When I declare the Trove 2.0.2 dependency explicitly in my project, it compiles fine.

I wonder about the optimal solution with regard to dkpro-core. In fact, the dependency on Trove 2.0.2. is declared in the Mallet pom.xml, so it does not seem to make sense to declare it in dkpro-core-mallet as well. On the other hand, how can wie ensure that another project depending on dkpro-core-mallet gets the right Trove version?

**Comment by reckart** [comment]
I'd suggest to open a bug with upstream mallet requesting to switch to a current version of trove - if there already is such an issue, mention it here. Otherwise, adding the dependency again to the DKPro Core module seems reasonable - with a corresponding comment in the POM and you'll also have to add an exclude for the Maven dependency analyzer plugin. It will not finally resolve the problem, but alleviate it. If a user still has problems with Maven choosing the "wrong" version, then they should add an explicit dependency on version 2 to their respective projects.

**Comment by carschno** [comment]
The issue has been discussed in Mallet, but apparently won't be resolved: https://github.com/mimno/Mallet/pull/17

**Comment by carschno** [comment]
@reckart We recently discussed a potential input file format suitable for mmap. I've understood the following outline: list all tokens at the beginning of the file (one per line), then list the vectors as sequences of `n` float/double values in the remainder of the file. Hence, the 1st token string in the input file is mapped to a vector of the 1st `n` binary float/double values. `n` is the dimensionality of the embeddings.

Two questions:

1. How can we determine the end of the string token list and the beginning of the vectors? The first line of the file could hold the number of total strings, or is there a better solution? Likewise for the dimensionality of the embedding vectors: encode `n` in the first line of the file?

2. How should the float/double values be stored in a file? In a binary format? Use `Float#floatToIntBits()` (or `Double#doubleToLongBits()`)?

**Comment by carschno** [comment]
It appears to remain necessary for child projects to declare the Trove dependency explicitly anyway, but this needs to be resolved in Mallet.

**Comment by alaindesilets** [comment]
I have this same issue, but when I try to add a trove  2.x dependency in my project (any project for that matter), Maven complains that it can't find this module. For example, if I try to do mvn install on the attached pom.xml, I get the following error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.636 s
[INFO] Finished at: 2019-10-23T12:07:58-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TroveSpike: Could not resolve dependencies for project ca.nrc:TroveSpike:jar:0.0.1-SNAPSHOT: Could not find artifact trove:trove:jar:2.0.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException


[pom.xml.zip](https://github.com/dkpro/dkpro-core/files/3763359/pom.xml.zip)

**Comment by alaindesilets** [comment]
Nevermind. I was using the wrong artifact definition. I now used this and it's fine:

	<dependency>
	    <groupId>net.sf.trove4j</groupId>
	    <artifactId>trove4j</artifactId>
	    <version>2.1.0</version>
	</dependency>
